fluzo_contact_homepage_es:
    pattern:  /contacto
    defaults: { _controller: FluzoContactBundle:Default:index }    

fluzo_contact_homepage_en:
    pattern:  /contact
    defaults: { _controller: FluzoContactBundle:Default:index }  
    
fluzo_contact_submit:
    pattern: /contactok
    defaults: { _controller: FluzoContactBundle:Default:submit }  

    